---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(tidytext)
```

```{r}
text = c("To be, or not to be--that is the question:",
         "Whether 'tis nobler in the mind to suffer",
         "The slings and arrows of outrageous fortune",
         "Or to take arms against a sea of troubles",
         "And by opposing end them.")

text <- tibble(line=1:5, text=text)
text
```

```{r}
tokens <- text %>% unnest_tokens(word, text)
tokens
```

```{r}
tokens %>% count(word, sort = TRUE)
```

```{r}
lines <- readLines("https://chryswoods.com/text_analysis_r/hamlet.txt")
lines
```

```{r}
hamlet <- tibble(line=1:length(lines), text=lines)
hamlet_tokens <- hamlet %>% unnest_tokens(word, text)
hamlet_tokens %>% count(word, sort = TRUE)
```
```{r}
data(stop_words)
stop_words
```

```{r}
important_hamlet_tokens <- hamlet_tokens %>% anti_join(stop_words)
important_hamlet_tokens
```

```{r}
important_hamlet_tokens %>% count(word, sort=TRUE)
```

```{r}
hamlet %>% unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  count(word, sort = TRUE)
```

```{r}
library(gutenbergr)
```

```{r}
grimm_tales <- gutenberg_download(2591)
grimm_tales
```

```{r}
grimm_tales %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  count(word, sort = TRUE)
```

```{r}
counts <- grimm_tales %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  count(word, sort = TRUE) %>%
  filter(n > 100)

counts
```

```{r}
counts <- counts %>% mutate(word = reorder(word, n))
```

```{r}
counts %>% ggplot(aes(n, word)) + geom_col() + labs(y=NULL)
```

```{r}
sentiments <- get_sentiments("nrc")
sentiments
```

```{r}
sentiments %>% count(sentiment)
```

```{r}
grimm_tales <- gutenberg_download(2591) %>%
              unnest_tokens(word, text) %>%
              anti_join(stop_words)
grimm_tales
```

```{r}
grimm_tales_sentiments <- grimm_tales %>% inner_join(sentiments)
grimm_tales_sentiments
```

```{r}
grimm_tales_sentiments %>% 
  filter(sentiment=="positive") %>%
  count(word, sort=TRUE)
```

```{r}
grimm_tales_sentiments %>%
  filter(sentiment=="joy") %>%
  count(word) %>% 
  summarise(total=sum(n))
```

```{r}
grimm_tales_sentiments %>% count(sentiment)
```

```{r}
grimm_tales_sentiments %>%
  count(sentiment) %>%
  mutate(sentiment = reorder(sentiment, n)) %>%
  ggplot(aes(n, sentiment)) + geom_col() + labs(y=NULL)
```

```{r}
grimm_tales <- gutenberg_download(2591) %>% 
              mutate(linenumber=row_number()) %>% 
              unnest_tokens(word, text) %>% anti_join(stop_words)
grimm_tales
```

```{r}
grimm_tales_sentiments <- grimm_tales %>% 
                         inner_join(sentiments)
grimm_tales_sentiments
```

```{r}
grimm_tales_blocks <- grimm_tales_sentiments %>% 
                     count(block=linenumber%/%80, sentiment)
grimm_tales_blocks
```

```{r}
grimm_tales_blocks <- grimm_tales_blocks %>% 
                     pivot_wider(names_from = sentiment, 
                                 values_from = n, 
                                 values_fill = 0)
grimm_tales_blocks
```

```{r}
grimm_tales_blocks <- grimm_tales_blocks %>%
                         mutate(sentiment = positive - negative)
grimm_tales_blocks
```

```{r}
grimm_tales_blocks %>% ggplot(aes(block, sentiment)) + geom_col()
```

```{r}
grimm_tales_blocks %>% ggplot(aes(block, joy)) + geom_col()
```

```{r}
library(wordcloud)
```

```{r}
grimm_tales_count <- grimm_tales %>% count(word, sort = TRUE)
```

```{r}
wordcloud(grimm_tales_count$word, grimm_tales_count$n, 
          min.freq = 25, max.words = 50, random.order = FALSE)
```

```{r}
grimm_tales_count %>% with(wordcloud(word, n, 
          min.freq = 25, max.words = 50, random.order = FALSE))
```

```{r}
grimm_tales_count %>% with(wordcloud(word, n, 
          min.freq = 25, max.words = 50, random.order = FALSE,
          colors=brewer.pal(8, "Dark2")))
```
```{r}
grimm_tales_sentiments <- grimm_tales %>% 
                         inner_join(sentiments) %>% 
                         count(word, sentiment, sort=TRUE) %>% 
                         pivot_wider(names_from=sentiment, 
                                     values_from=n, 
                                     values_fill=0)
```

```{r}
grimm_tales_sentiments %>% with(wordcloud(word, joy, 
                                       min.freq=15,
                                       random.color = FALSE,
                                       colors = brewer.pal(8, "PuOr")))
```

```{r}
grimm_tales_sentiments %>% with(wordcloud(word, fear, 
                                       min.freq=10,
                                       random.color = FALSE,
                                       colors = brewer.pal(12, "Paired")))
```

```{r}
grimm_tales <- gutenberg_download(2591) %>% 
              mutate(linenumber=row_number())
```

```{r}
grimm_tales_bigrams <- grimm_tales %>% 
  unnest_tokens(bigram, text, token = "ngrams", n = 2)
grimm_tales_bigrams
```

```{r}
grimm_tales_bigrams <- grimm_tales_bigrams %>%
      separate(bigram, c("word1", "word2"), sep = " ") 
grimm_tales_bigrams
```

```{r}
data(stop_words)

grimm_tales_bigrams <- grimm_tales_bigrams %>%
      filter(!word1 %in% stop_words$word) %>%
      filter(!word2 %in% stop_words$word)

grimm_tales_bigrams
```

```{r}
grimm_tales_bigrams <- grimm_tales_bigrams %>%
                      filter(!is.na(word1)) %>% 
                      filter(!is.na(word2))
grimm_tales_bigrams
```

```{r}
grimm_tales_bigrams <- grimm_tales_bigrams %>%
                      unite(bigram, word1, word2, sep=" ")
grimm_tales_bigrams
```

```{r}
grimm_tales_bigrams <- grimm_tales %>% 
                      unnest_tokens(bigram, text, token = "ngrams", n = 2) %>%
                      separate(bigram, c("word1", "word2"), sep = " ") %>%
                      filter(!word1 %in% stop_words$word) %>%
                      filter(!word2 %in% stop_words$word) %>%
                      filter(!is.na(word1)) %>% 
                      filter(!is.na(word2)) %>% 
                      unite(bigram, word1, word2, sep=" ")

grimm_tales_bigrams
```

```{r}
bigram_counts <- grimm_tales_bigrams %>% count(bigram, sort=TRUE)
bigram_counts
```

```{r}
bigram_counts <- grimm_tales %>% 
                      unnest_tokens(bigram, text, token = "ngrams", n = 2) %>%
                      separate(bigram, c("word1", "word2"), sep = " ") %>%
                      filter(!word1 %in% stop_words$word) %>%
                      filter(!word2 %in% stop_words$word) %>%
                      filter(!is.na(word1)) %>% 
                      filter(!is.na(word2)) %>% 
                      count(word1, word2, sort=TRUE)

bigram_counts
```

```{r}
library(igraph)

bigram_graph <- bigram_counts %>%
                  filter(n >= 7) %>%
                  graph_from_data_frame()
bigram_graph
```

```{r}
library(ggraph)

ggraph(bigram_graph, layout = "fr") +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1)
```

```{r}
ggraph(bigram_graph, layout = "fr") +
     geom_edge_link(aes(edge_alpha = n), show.legend = FALSE,
                    arrow = grid::arrow(type = "closed", length = unit(2, "mm")), 
                    end_cap = circle(1, "mm")) +
     geom_node_point(color = "lightblue", size = 2) +
     geom_node_text(aes(label = name), size = 2) +
     theme_void()
```

```{r}
bigram_graph <- bigram_counts %>%
    filter(n >= 3) %>%
    graph_from_data_frame()

ggraph(bigram_graph, layout = "fr") +
     geom_edge_link(aes(edge_alpha = n), show.legend = FALSE,
                    arrow = grid::arrow(type = "closed", length = unit(1, "mm")), 
                    end_cap = circle(0.5, "mm")) +
     geom_node_point(color = "lightblue", size = 0.5) +
     geom_node_text(aes(label = name), size = 1) +
     theme_void()
```

```{r}

```

```{r}
grimm_tales <- gutenberg_download(2591) %>% 
              mutate(linenumber=row_number())
```

```{r}
grimm_tales_trigrams <- grimm_tales %>% 
  unnest_tokens(trigram, text, token = "ngrams", n = 3)
grimm_tales_trigrams
```

```{r}
grimm_tales_trigrams <- grimm_tales_trigrams %>%
      separate(trigram, c("word1", "word2", "word3"), sep = " ") 
grimm_tales_trigrams
```

```{r}
grimm_tales_trigrams <- grimm_tales_trigrams %>%
                      filter(!is.na(word1)) %>% 
                      filter(!is.na(word2)) %>%
   filter(!is.na(word3))
grimm_tales_trigrams
```

```{r}
grimm_tales_bigrams <- grimm_tales_trigrams %>%
                      unite(trigram, word1, word2, word3, sep=" ")
grimm_tales_trigrams
```

```{r}
grimm_tales_trigrams <- grimm_tales %>% 
                      unnest_tokens(trigram, text, token = "ngrams", n = 3) %>%
                      separate(trigram, c("word1", "word2", "word3"), sep = " ") %>%
                      filter(!is.na(word1)) %>% 
                      filter(!is.na(word2)) %>%
                      filter(!is.na(word3)) %>%
                      unite(trigram, word1, word2, word3, sep=" ")

grimm_tales_trigrams
```

```{r}
trigram_counts <- grimm_tales_trigrams %>% count(trigram, sort=TRUE)
trigram_counts
```

```{r}
trigram_counts <- grimm_tales %>% 
                      unnest_tokens(trigram, text, token = "ngrams", n = 3) %>%
                      separate(trigram, c("word1", "word2", "word3"), sep = " ") %>%
                      filter(!is.na(word1)) %>% 
                      filter(!is.na(word2)) %>% 
  filter(!is.na(word3)) %>% 
                      count(word1, word2, word3, sort=TRUE)

trigram_counts
```

```{r}
library(igraph)

trigram_graph <- trigram_counts %>%
                  filter(n >= 7) %>%
                  graph_from_data_frame()
trigram_graph
```

```{r}
library(ggraph)

ggraph(trigram_graph, layout = "fr") +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1)
```

```{r}
ggraph(trigram_graph, layout = "fr") +
     geom_edge_link(aes(edge_alpha = n), show.legend = FALSE,
                    arrow = grid::arrow(type = "closed", length = unit(2, "mm")), 
                    end_cap = circle(1, "mm")) +
     geom_node_point(color = "lightblue", size = 2) +
     geom_node_text(aes(label = name), size = 2) +
     theme_void()
```

```{r}
trigram_graph <- trigram_counts %>%
    filter(n >= 3) %>%
    graph_from_data_frame()

ggraph(trigram_graph, layout = "fr") +
     geom_edge_link(aes(edge_alpha = n), show.legend = FALSE,
                    arrow = grid::arrow(type = "closed", length = unit(1, "mm")), 
                    end_cap = circle(0.5, "mm")) +
     geom_node_point(color = "lightblue", size = 0.5) +
     geom_node_text(aes(label = name), size = 1) +
     theme_void()

```

```{r}
# Define the soliloquy
hamlet_soliloquy <- "
To be, or not to be, that is the question:
Whether 'tis nobler in the mind to suffer
The slings and arrows of outrageous fortune,
Or to take Arms against a Sea of troubles,
And by opposing end them: to die, to sleep
No more; and by a sleep, to say we end
The heartache, and the thousand natural shocks
That Flesh is heir to? 'tis a consummation
Devoutly to be wished. To die, to sleep,
To sleep, perchance to Dream; aye, there's the rub,
For in that sleep of death, what dreams may come,
When we have shuffled off this mortal coil,
Must give us pause..."

# Convert the text to a tibble
hamlet_tibble <- tibble(line = 1, text = hamlet_soliloquy)

# Create bigrams
hamlet_bigrams <- hamlet_tibble %>% 
  unnest_tokens(bigram, text, token = "ngrams", n = 2)

# Separate into individual words
hamlet_bigrams <- hamlet_bigrams %>%
  separate(bigram, c("word1", "word2"), sep = " ")
```

```{r}
# Count the bigrams
bigram_counts <- hamlet_bigrams %>% count(word1, word2, sort = TRUE)

# Generate the graph
bigram_graph <- bigram_counts %>%
  graph_from_data_frame()

# Plot the graph
ggraph(bigram_graph, layout = "fr") +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1) +
  theme_void()
```

```{r}


```
